{% set name = "linearmodels" %}
{% set version = "4.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a302623ab4492a5126c8229cf27eb6bfb55d2b9a3c212e71e33e00c0e872ca2d

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]

  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
    - cython
    # Do not add any constraint on numpy here to use global pinning
    - numpy
    - mypy_extensions >=0.4
    - pandas >=0.24
    - patsy
    - property_cached >=1.6.3
    - scipy >=1.2
    - statsmodels >=0.11
  run:
    - python
    - cython
    - mypy_extensions >=0.4
    - {{ pin_compatible('numpy') }}
    - pandas >=0.24
    - patsy
    - property_cached >=1.6.3
    - scipy >=1.2
    - statsmodels >=0.11
    - pyhdfe >=0.1
    - formulaic >=0.3
    - setuptools-scm
test:
  imports:
    - linearmodels
    - linearmodels.asset_pricing
    - linearmodels.compat
    - linearmodels.datasets
    - linearmodels.datasets.birthweight
    - linearmodels.datasets.card
    - linearmodels.datasets.fertility
    - linearmodels.datasets.french
    - linearmodels.datasets.fringe
    - linearmodels.datasets.jobtraining
    - linearmodels.datasets.meps
    - linearmodels.datasets.mroz
    - linearmodels.datasets.munnell
    - linearmodels.datasets.wage
    - linearmodels.datasets.wage_panel
    - linearmodels.iv
    - linearmodels.panel
    - linearmodels.system
    - linearmodels.tests
    - linearmodels.tests.asset_pricing
    - linearmodels.tests.datasets
    - linearmodels.tests.iv
    - linearmodels.tests.iv.results
    - linearmodels.tests.panel
    - linearmodels.tests.panel.results
    - linearmodels.tests.system
    - linearmodels.tests.system.results
    - linearmodels.typing

about:
  home: http://github.com/bashtage/linearmodels
  license: NCSA
  license_family: OTHER
  license_file: LICENSE.md
  summary: Instrumental Variable and Linear Panel models for Python
  description: |
    Linear (regression) models for Python. Extends statsmodels with Panel
    regression, instrumental variable estimators, system estimators and
    models for estimating asset pricing models.
  doc_url: https://bashtage.github.io/linearmodels
  dev_url: https://github.com/bashtage/linearmodels

extra:
  recipe-maintainers:
    - khwilson
    - bashtage
