{% set name = "linearmodels" %}
{% set version = "5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2642be561fedbd9351479f9c1587e02bb3ff4972954044e5353a9bcfa8d366a9

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.34                       # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - cython >=0.29.34
    # Do not add any constraint on numpy here to use global pinning
    - numpy
    - pandas >=1.1
    - scipy >=1.5
    - statsmodels >=0.12
  run:
    - python
    - mypy_extensions >=0.4
    - {{ pin_compatible('numpy') }}
    - pandas >=1.1
    - scipy >=1.5
    - statsmodels >=0.12
    - pyhdfe >=0.1
    - formulaic >=0.6.1
test:
  imports:
    - linearmodels
    - linearmodels.asset_pricing
    - linearmodels.compat
    - linearmodels.datasets
    - linearmodels.datasets.birthweight
    - linearmodels.datasets.card
    - linearmodels.datasets.fertility
    - linearmodels.datasets.french
    - linearmodels.datasets.fringe
    - linearmodels.datasets.jobtraining
    - linearmodels.datasets.meps
    - linearmodels.datasets.mroz
    - linearmodels.datasets.munnell
    - linearmodels.datasets.wage
    - linearmodels.datasets.wage_panel
    - linearmodels.iv
    - linearmodels.panel
    - linearmodels.system
    - linearmodels.tests
    - linearmodels.tests.asset_pricing
    - linearmodels.tests.datasets
    - linearmodels.tests.iv
    - linearmodels.tests.iv.results
    - linearmodels.tests.panel
    - linearmodels.tests.panel.results
    - linearmodels.tests.system
    - linearmodels.tests.system.results
    - linearmodels.typing

about:
  home: http://github.com/bashtage/linearmodels
  license: NCSA
  license_family: OTHER
  license_file: LICENSE.md
  summary: Instrumental Variable and Linear Panel models for Python
  description: |
    Linear (regression) models for Python. Extends statsmodels with Panel
    regression, instrumental variable estimators, system estimators and
    models for estimating asset pricing models.
  doc_url: https://bashtage.github.io/linearmodels
  dev_url: https://github.com/bashtage/linearmodels

extra:
  recipe-maintainers:
    - khwilson
    - bashtage
